FROM mcr.microsoft.com/dotnet/sdk:6.0

WORKDIR /core
COPY core/*.csproj ./
RUN dotnet restore

COPY core/. ./

WORKDIR ../app
COPY words/*.csproj ./
RUN dotnet restore

COPY words/. ./

EXPOSE 5000
RUN dotnet dev-certs https
ENTRYPOINT ["dotnet", "watch", "run"];