FROM node:14-alpine

# ARG REACT_APP_ENV=${INPUT_REACT_APP_ENV}

# ENV REACT_APP_ENV=${INPUT_REACT_APP_ENV}

RUN npm install -g serve --silent

COPY package*.json ./
RUN npm install --silent

COPY . .
RUN REACT_APP_ENV=qa npm run build

CMD serve -p $PORT -s dist