FROM node:14-alpine

ARG REACT_APP_ENV=${REACT_APP_ENV}

ENV REACT_APP_ENV=${REACT_APP_ENV}

RUN npm install -g serve --silent

COPY package*.json ./
RUN npm install --silent

COPY . .
RUN REACT_APP_ENV=${REACT_APP_ENV} npm run build

CMD serve -p $PORT -s dist